---
micronaut:
  environment: local
  security.token.jwt.signatures.secret.generator.secret: mashkeyboardeifieyalkdklfmcidh
---
tech:
  garymyers:
    security:
      jwt:
        pem:
          path: "classpath:security/local-jwt.pem" #openssl genrsa -out security/local-jwt.pem 2048
