---
micronaut:
  application:
    name: tech-garymyers-micronaut-security

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: /api/login
      logout:
        enabled: true
        path: /api/logout
    token:
      jwt:
        enabled: true
        generator:
          access-token-expiration: 43200 # 12 hours
          refresh-token-expiration: 86400 # 24 hours
        berer:
          enabled: true
        signatures:
          secret:
            generator:
              jws-algorithm: HS256